// =============================================================================
// Vector Architect — Core Blueprint Data Types
// All dimensions are in MILLIMETERS. All coordinates are in canvas pixels.
// 1 canvas pixel = 10mm (1cm). 100px = 1 meter.
// =============================================================================

/** 2D coordinate on the canvas */
export interface Point2D {
  x: number;
  y: number;
}

/** Axis-aligned bounding box */
export interface BoundingBox {
  minX: number;
  minY: number;
  maxX: number;
  maxY: number;
}

// =============================================================================
// Layers
// =============================================================================

export type Layer = 'walls' | 'furniture' | 'electrics' | 'plumbing';

export const ALL_LAYERS: readonly Layer[] = [
  'walls',
  'furniture',
  'electrics',
  'plumbing',
] as const;

export const LAYER_LABELS: Record<Layer, string> = {
  walls: 'WALLS',
  furniture: 'FURNITURE',
  electrics: 'ELECTRICS',
  plumbing: 'PLUMBING',
};

// =============================================================================
// Wall System
// =============================================================================

/** A connection point where walls meet */
export interface WallNode {
  id: string;
  position: Point2D;
}

/** A wall segment between two nodes */
export interface Wall {
  id: string;
  startNodeId: string;
  endNodeId: string;
  /** Wall thickness in mm (default: 200mm) */
  thickness: number;
  /** Wall height in mm (default: 2700mm) */
  height: number;
}

// =============================================================================
// Smart Objects
// =============================================================================

export type SmartObjectType =
  // Furniture
  | 'door'
  | 'window'
  | 'bed'
  | 'sofa'
  | 'table'
  | 'chair'
  | 'wardrobe'
  // Electrics
  | 'socket'
  | 'switch'
  | 'light'
  // Plumbing
  | 'pipe'
  | 'drain'
  | 'sink'
  | 'shower'
  | 'toilet'
  // Smart Appliances (generate children)
  | 'dishwasher'
  | 'washing_machine'
  | 'oven';

/** Which layer each object type belongs to */
export const OBJECT_LAYER_MAP: Record<SmartObjectType, Layer> = {
  door: 'walls',
  window: 'walls',
  bed: 'furniture',
  sofa: 'furniture',
  table: 'furniture',
  chair: 'furniture',
  wardrobe: 'furniture',
  socket: 'electrics',
  switch: 'electrics',
  light: 'electrics',
  pipe: 'plumbing',
  drain: 'plumbing',
  sink: 'plumbing',
  shower: 'plumbing',
  toilet: 'plumbing',
  dishwasher: 'furniture',
  washing_machine: 'furniture',
  oven: 'furniture',
};

/** A parametric object placed on the canvas */
export interface SmartObject {
  id: string;
  type: SmartObjectType;
  layer: Layer;
  position: Point2D;
  /** Rotation in degrees (0–360) */
  rotation: number;
  /** Object width in mm */
  width: number;
  /** Object height/depth in mm */
  height: number;
  /** If this object was auto-generated by a parent */
  parentId?: string;
  /** Whether this was auto-generated by the smart preset system */
  isAutoGenerated: boolean;
  /** Height from floor in mm (relevant for sockets, switches) */
  heightFromFloor?: number;
}

// =============================================================================
// Wet Zones (for conflict detection)
// =============================================================================

/** A polygon defining a wet zone (shower, bathtub area) */
export interface WetZone {
  id: string;
  /** Polygon vertices defining the zone boundary */
  vertices: Point2D[];
  /** Restriction radius in mm (default: 600mm) */
  restrictionRadius: number;
}

// =============================================================================
// Auto-Routing
// =============================================================================

/** A route path computed by the server */
export interface RoutePath {
  id: string;
  layer: Layer;
  /** Ordered waypoints of the route */
  points: Point2D[];
  /** Display color (hex) */
  color: string;
}

// =============================================================================
// Room & Project (top-level containers)
// =============================================================================

export interface Room {
  id: string;
  name: string;
  walls: Wall[];
  wallNodes: WallNode[];
  objects: SmartObject[];
  wetZones: WetZone[];
  routes: RoutePath[];
}

export interface Project {
  id: string;
  name: string;
  rooms: Room[];
  activeRoomId: string;
  createdAt: number;
  updatedAt: number;
}

// =============================================================================
// Camera / Viewport
// =============================================================================

export interface CameraState {
  x: number;
  y: number;
  zoom: number;
}

// =============================================================================
// Design System Constants
// =============================================================================

export const COLORS = {
  BLACK: '#000000',
  WHITE: '#FFFFFF',
  DANGER: '#FF3B30',
  SUCCESS: '#34C759',
  ACTIVE: '#FFCC00',
  GRID_MINOR: '#E0E0E0',
  GRID_MAJOR: '#BDBDBD',
  ROUTE_ELECTRIC: '#FFCC00',
  ROUTE_PLUMBING: '#007AFF',
} as const;

export const GRID = {
  /** Minor grid spacing in canvas pixels (= 100mm) */
  MINOR_SPACING: 10,
  /** Major grid spacing in canvas pixels (= 1000mm / 1m) */
  MAJOR_SPACING: 100,
} as const;

export const DEFAULTS = {
  WALL_THICKNESS: 200,
  WALL_HEIGHT: 2700,
  WET_ZONE_RESTRICTION: 600,
  SMART_OFFSET: 600,
} as const;
