// =============================================================================
// Vector Architect — Domain Model & Global Types
// Defines the strict mathematical and logical structures of the CAD system.
// =============================================================================

// =============================================================================
// Core Geometry & Primitives
// =============================================================================

export interface Point2D {
  x: number;
  y: number;
}

export type Layer = 'walls' | 'furniture' | 'electrics' | 'plumbing';

// =============================================================================
// Architecture Components (Walls & Nodes)
// =============================================================================

export interface WallNode {
  id: string;
  position: Point2D;
}

export interface Wall {
  id: string;
  startNodeId: string;
  endNodeId: string;
  thickness: number;
  height: number;
}

// =============================================================================
// Smart Objects & Automation
// =============================================================================

export type SmartObjectType =
  // Electrics
  | 'socket_220v'
  | 'socket_internet'
  | 'light_switch'
  | 'electric_panel'
  // Furniture & Appliances
  | 'bed_queen'
  | 'sofa_standard'
  | 'dishwasher_builtin'
  | 'oven_builtin'
  | 'router_wifi'
  // Plumbing
  | 'toilet'
  | 'sink'
  | 'shower_cabin';

export interface SmartObject {
  id: string;
  type: SmartObjectType;
  layer: Layer;
  position: Point2D;
  rotation: number; // In radians or degrees (standardized in radians for Math functions)
  width: number;
  height: number;
  // Automation specific
  isAutoGenerated: boolean;
  parentId?: string; // If this object was spawned by another (e.g., socket spawned by dishwasher)
}

// =============================================================================
// Safety & Anti-Fool Systems
// =============================================================================

export interface WetZone {
  id: string;
  vertices: Point2D[];
  restrictionRadius: number; // Minimum safe distance for electrics (e.g., 600mm)
}

export interface RoutePath {
  id: string;
  points: Point2D[];
  type: 'electric_main' | 'electric_light' | 'water_cold' | 'water_hot' | 'drainage';
}

// =============================================================================
// Container Structures (Room & Project)
// =============================================================================

export interface Room {
  id: string;
  name: string;
  wallNodes: WallNode[];
  walls: Wall[];
  objects: SmartObject[];
  wetZones: WetZone[];
  routes: RoutePath[];
}

export interface Project {
  id: string;
  name: string;
  activeRoomId: string;
  rooms: Room[];
  createdAt: number;
  updatedAt: number;
}

// =============================================================================
// Constants & Configuration Maps
// =============================================================================

/**
 * Maps each smart object type to its corresponding strict layer.
 * Prevents sockets from rendering on the furniture layer.
 */
export const OBJECT_LAYER_MAP: Record<SmartObjectType, Layer> = {
  socket_220v: 'electrics',
  socket_internet: 'electrics',
  light_switch: 'electrics',
  electric_panel: 'electrics',
  
  bed_queen: 'furniture',
  sofa_standard: 'furniture',
  dishwasher_builtin: 'furniture',
  oven_builtin: 'furniture',
  router_wifi: 'furniture',
  
  toilet: 'plumbing',
  sink: 'plumbing',
  shower_cabin: 'plumbing',
};

/**
 * Grid spacing constants in canvas pixels.
 * MINOR_SPACING = smallest snapping unit (100mm).
 * MAJOR_SPACING = large grid subdivision (500mm).
 */
export const GRID = {
  MINOR_SPACING: 10,  // 100mm / 10px per mm = 10 canvas pixels
  MAJOR_SPACING: 50,  // 500mm = 50 canvas pixels
};

/**
 * Global architectural defaults in millimeters.
 */
export const DEFAULTS = {
  WALL_THICKNESS: 200, // 200mm standard internal load-bearing
  WALL_HEIGHT: 2700,   // 2.7m ceiling
  GRID_SIZE: 100,      // 100mm grid step for snapping
  WET_ZONE_RESTRICTION: 600, // 600mm restriction around water sources (СНиП/ПУЭ standard)
};

/**
 * Semantic Design System Colors (Strict Black & White with technical accents)
 * NO ORANGE. NO GRADIENTS.
 */
export const COLORS = {
  // Base
  WHITE: '#FFFFFF',
  BLACK: '#000000',
  BACKGROUND: '#F9F9F9',
  GRID_LINE: '#E5E5E5',
  
  // Semantic / Interactive
  DANGER: '#FF3B30',  // System Red (Conflicts, Deletion)
  SUCCESS: '#34C759', // System Green (Save, Apply)
  ACTIVE: '#FFCC00',  // System Yellow (Selection, Auto-Routing paths)
  
  // Specific routes
  WATER_COLD: '#007AFF', // Blue only for plumbing routes to distinguish from electrics
};