// =============================================================================
// Vector Architect — Smart Preset Automation
// Defines parent-child relationships for smart appliances.
// =============================================================================

import {
  SmartObjectType,
  Layer,
  SmartObject,
  Point2D,
  DEFAULTS,
} from '@/types/blueprint';
import { mmToCanvas } from '@/utils/snapping';

/** Definition of a child object auto-generated by a parent */
export interface ChildPreset {
  type: SmartObjectType;
  layer: Layer;
  /** Offset from parent in mm (X axis, relative to parent rotation) */
  offsetX: number;
  /** Offset from parent in mm (Y axis, relative to parent rotation) */
  offsetY: number;
  /** Default width in mm */
  width: number;
  /** Default height in mm */
  height: number;
  /** Height from floor in mm */
  heightFromFloor?: number;
}

/**
 * Smart preset rules: when a parent object is placed,
 * these child objects are automatically generated.
 */
export const SMART_PRESETS: Partial<Record<SmartObjectType, ChildPreset[]>> = {
  dishwasher: [
    {
      type: 'socket',
      layer: 'electrics',
      offsetX: DEFAULTS.SMART_OFFSET,
      offsetY: 0,
      width: 80,
      height: 80,
      heightFromFloor: 300,
    },
    {
      type: 'drain',
      layer: 'plumbing',
      offsetX: DEFAULTS.SMART_OFFSET,
      offsetY: 100,
      width: 50,
      height: 50,
    },
  ],
  washing_machine: [
    {
      type: 'socket',
      layer: 'electrics',
      offsetX: DEFAULTS.SMART_OFFSET,
      offsetY: 0,
      width: 80,
      height: 80,
      heightFromFloor: 300,
    },
    {
      type: 'drain',
      layer: 'plumbing',
      offsetX: DEFAULTS.SMART_OFFSET,
      offsetY: 100,
      width: 50,
      height: 50,
    },
  ],
  oven: [
    {
      type: 'socket',
      layer: 'electrics',
      offsetX: DEFAULTS.SMART_OFFSET,
      offsetY: 0,
      width: 80,
      height: 80,
      heightFromFloor: 900,
    },
  ],
};

/**
 * Calculate the world position of a child object given the parent's
 * position, rotation, and the child's offset.
 */
export function calculateChildPosition(
  parentPosition: Point2D,
  parentRotationDeg: number,
  offsetXMm: number,
  offsetYMm: number,
): Point2D {
  const rad = (parentRotationDeg * Math.PI) / 180;
  const offsetXPx = mmToCanvas(offsetXMm);
  const offsetYPx = mmToCanvas(offsetYMm);

  return {
    x: parentPosition.x + offsetXPx * Math.cos(rad) - offsetYPx * Math.sin(rad),
    y: parentPosition.y + offsetXPx * Math.sin(rad) + offsetYPx * Math.cos(rad),
  };
}

/**
 * Generate child SmartObjects for a given parent.
 * Returns an array of child objects ready to be added to the store.
 */
export function generateChildObjects(
  parent: SmartObject,
  idGenerator: () => string,
): SmartObject[] {
  const presets = SMART_PRESETS[parent.type];
  if (!presets) return [];

  return presets.map((preset) => {
    const position = calculateChildPosition(
      parent.position,
      parent.rotation,
      preset.offsetX,
      preset.offsetY,
    );

    return {
      id: idGenerator(),
      type: preset.type,
      layer: preset.layer,
      position,
      rotation: parent.rotation,
      width: preset.width,
      height: preset.height,
      parentId: parent.id,
      isAutoGenerated: true,
      heightFromFloor: preset.heightFromFloor,
    };
  });
}
