// =============================================================================
// Vector Architect — Smart Presets & Automation Engine
// Generates automated child objects (sockets, switches) based on parent placement.
// =============================================================================

import { SmartObject, SmartObjectType, OBJECT_LAYER_MAP } from '../types/blueprint';

/**
 * Генерирует массив зависимых объектов (розеток, выключателей) 
 * на основе типа и положения родительского объекта (мебели/техники).
 */
export function generateChildObjects(
  parent: SmartObject,
  generateId: () => string
): SmartObject[] {
  const children: SmartObject[] = [];

  /**
   * Внутренняя функция для точного позиционирования дочернего элемента.
   * Учитывает угол поворота (rotation) родителя с помощью матрицы вращения.
   * * @param type Тип объекта (например, 'socket_220v')
   * @param offsetX Смещение по оси X (влево/вправо от центра родителя)
   * @param offsetY Смещение по оси Y (вверх/вниз от центра родителя)
   */
  const createChild = (
    type: SmartObjectType,
    offsetX: number,
    offsetY: number,
    width: number = 40,
    height: number = 40
  ): SmartObject => {
    // Математика: Вращаем точку смещения вокруг центра родителя
    const rad = parent.rotation;
    const rotatedOffsetX = offsetX * Math.cos(rad) - offsetY * Math.sin(rad);
    const rotatedOffsetY = offsetX * Math.sin(rad) + offsetY * Math.cos(rad);

    return {
      id: generateId(),
      type,
      layer: OBJECT_LAYER_MAP[type],
      position: {
        x: parent.position.x + rotatedOffsetX,
        y: parent.position.y + rotatedOffsetY,
      },
      rotation: parent.rotation, // Розетка смотрит туда же, куда и родитель
      width,
      height,
      isAutoGenerated: true,
      parentId: parent.id, // Жесткая привязка к родителю!
    };
  };

  // =============================================================================
  // БИБЛИОТЕКА ПРЕСЕТОВ И СНиПов
  // =============================================================================
  switch (parent.type) {
    case 'dishwasher_builtin':
      // ПРАВИЛО: Розетку для встраиваемой посудомойки запрещено ставить прямо за ней.
      // Автоматически выносим розетку на 600мм в сторону (в соседний шкафчик).
      children.push(createChild('socket_220v', 600, 0));
      // Можно также добавить вывод канализации (drainage), если расширим типы
      break;

    case 'oven_builtin':
      // Духовой шкаф — аналогично, розетка уходит вбок или в цоколь.
      children.push(createChild('socket_220v', 600, 0));
      break;

    case 'router_wifi':
      // Умный спавн для роутера: всегда нужны и питание, и витая пара рядом.
      children.push(createChild('socket_220v', -45, 0));
      children.push(createChild('socket_internet', 45, 0));
      break;

    case 'bed_queen':
      // Двуспальная кровать (~1600мм ширина). 
      // Спавним розетки и выключатели бра прямо над прикроватными тумбами.
      
      // Левая тумба (отступаем 900мм влево от центра кровати)
      children.push(createChild('socket_220v', -900, -200));
      children.push(createChild('light_switch', -1000, -200));
      
      // Правая тумба (отступаем 900мм вправо)
      children.push(createChild('socket_220v', 900, -200));
      children.push(createChild('light_switch', 1000, -200));
      break;

    default:
      // Обычные объекты (например, одиночный диван) ничего не генерируют
      break;
  }

  return children;
}